version: '3'

services:
  seeddb:
    build: ./db
    depends_on:
      - 'database'
    links: 
      - database

  container:
    build: .
    depends_on:
      - 'seeddb'
    ports:
      - "3002:3002"

  database:
    image: mongo:latest
    ports:
      - "27017:27017"