version: '3'

services:
  menu:
    build: .
    depends_on:
      - 'database'
    ports:
      - '3002:3002'
  seed:
    build: .
    command: "npm run setup:db"

  database:
    image: mongo:latest